language: cpp

compiler:
  - gcc
  - clang
  
before_script:
  - ./configure 
  
script: scons
  
branches:
  only:
    - master

notifications:
  recipients:
    - gaetan@xeberon.net
  email:
    on_success: change
    on_failure: always